export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_BLOG_POST_SUCCESS = 'LOAD_BLOG_POST_SUCCESS';
export const CREATE_BLOG_POST_SUCCESS = 'CREATE_BLOG_POST_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';